version: '3.5'
services:
  server:
    build: ./server
    # image: your_custome_image_name
    # container_name: your_custom_container_name
    depends_on:
    - rabbit
    ports:
    - "1337:1337"
    # defining a network for this container.
    networks: 
      - rabbit_event_stream
    volumes:
      - servervol:/logs
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
    - RABBITMQ_HOSTNAME=rabbit
    - RABBITMQ_USER=guest
    - RABBITMQ_PASSWORD=guest
    ports:
      - "15672:15672" # RabbitMQ http API
      - "5672:5672"   # AMQP connection to RabbitMQ
    volumes:
      - rabbitvol:/var/lib/rabbitmq
    # defining a network for this container.
    networks:
      - rabbit_event_stream
volumes:
  rabbitvol:
  servervol:
networks: 
  # defining our rabbit_event_stream network
  rabbit_event_stream: 
    name: rabbit_event_stream